# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Colt's Code Journal
subtitle: Mostly C# and Unity
logo: "/assets/images/unity-csharp-icon.png"
description: >- # this means to ignore newlines until "baseurl:"
  The purpose of this site is to share insights into my day-to-day
  development experiences, mostly related to C# and game dev with Unity.
twitter_username: '@GameConstructor'
github_username: cabauman
minimal_mistakes_skin: air
repository: cabauman/cabauman.github.io
search: true

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-target-blank

author:
  name   : "Colt Bauman"
  avatar : "/assets/images/bio-photo.jpg"
  location : "South Korea"
  bio    : "A minimalist developer with a passion for game development, performance optimization, test writing, IoC, source generators, etc."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.coltscodejournal.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/@GameConstructor"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cabauman"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/@GameConstructor"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cabauman"

comments:
  provider: "giscus"
  giscus:
    repo_id: "MDEwOlJlcG9zaXRvcnk0MDE5Mzk4MzQ="
    category_name: "Announcements"
    category_id: "DIC_kwDOF_Udes4CdJl3"
    discussion_term: "pathname"
    reactions_enabled: '1'
    theme: "light"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
